name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build_linux_x86-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev

      - name: Configure Primal
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Primal
        run: cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/primal bin/primal_linux_x86-64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/primal_linux_x86-64

  build_linux_x86-64_openmp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev

      - name: Configure Primal
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGOMP=ON

      - name: Build Primal
        run: cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/primal bin/primal_linux_x86-64_openmp

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/primal_linux_x86-64_openmp

  build_windows_x86-64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: choco install boost-msvc-14.1

      - name: Configure Primal
        run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Primal
        run: cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/primal.exe bin/primal_windows_x86-64.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/primal_windows_x86-64.exe

  release:
    runs-on: ubuntu-latest
    needs: [build_linux_x86-64, build_linux_x86-64_openmp, build_windows_x86-64]

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Copy x86-64 Binaries to the Root Folder
        run: |
          cp artifact/primal_linux_x86-64 primal && cp artifact/primal_windows_x86-64.exe primal.exe

      - name: Create x86-64 Packages
        run: |
          zip -r primal_windows_x86-64.zip suprimal.exe LICENSE.md
          tar -czf primal_linux_x86-64.tar.gz primal LICENSE.md

      - name: Copy x86-64_openmp Binaries to the Root Folder
        run: |
          cp artifact/primal_linux_x86-64_openmp primal

      - name: Create x86-64_openmp Packages
        run: |
          tar -czf primal_linux_x86-64_openmp.tar.gz primal LICENSE.md

      - name: Release linux_x86-64 Version of Primal
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: primal_linux_x86-64.tar.gz
          tag: ${{github.ref}}

      - name: Release windows_x86-64 Version of Primal
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: primal_Windows_x86-64.tar.gz
          tag: ${{github.ref}}

      - name: Release linux_x86-64_openmp Version of Primal
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: primal_linux_x86-64_openmp.tar.gz
          tag: ${{github.ref}}
